spring.data.rest.basePath: /api
QuestionFile: "QuestionList.ods"
ThirdStageFile: "MOL.csv"
server.session.cookie.name: obsession
server.server-header: nginx/1.5.12
---
spring:
  profiles: production
  data:
    mongodb:
      database: questionnaire-ng
      host: ds015879.mlab.com
      password: ${mongo-password} # Vi taki dumaete zdes budet parol?
      port: 15879 # Mongo server port.
      username: questionnaire-1user
QuestionFile: "/QuestionList.ods"
ThirdStageFile: "/MOL.csv"