spring.data.rest.basePath: /api
mail:
  daemon:
    host: smtp.yandex.ru
    port: 465
    ssl: true
    email: zimy@yandex.ru
    username: zimy
    password: iVfmvMXRul5Js3j
    debug: false
QuestionFile: "/home/zimy/Documents/HotProjects/questionnaire-ng/src/main/resources/QuestionList.ods"
server.session.cookie.name: obsession
server.server-header: nginx/1.5.12